//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsTask.Model
{
    using System;
    using System.Collections.Generic;

    public partial class Students
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public int IndexNumber { get; set; }
        public string DateOfBirth { get; set; }
        public string Mark { get; set; }
    }
}
